[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
admin_passwd = change-this-before-production
db_host = db
db_port = 5432
db_user = odoo
db_password = change-me
proxy_mode = True
list_db = True
